device: cpu
model_name: CNNModel
model_args:
  log: True
  lr: 0.02
  lr_decay: 0.9
  adam_betas: [0.9, 0.999]
  kernel_size: 5
  stride: 1
  padding: 0
  hidden_dim: 256
  xavier_init: True
  out_act: sigmoid
dataset_args:
  d_type: train
  normalize: True
  bounds: [0, 1]
  sequence_length: 48
  future_steps: 1
dataloader_args:
  num_workers: 0
  batch_size: 512
  shuffle: True
train_epochs: 5
evaluation: None