device: cpu
model_name: PURE-CNN-Model
model_args:
  log: True
  lr: 0.003
  lr_decay: 0.9
  adam_betas: [0.9, 0.999]
  ch_in: 1
  ch_out: 10
  kernel_size: [4, 5]
  stride: 1
  padding: 0
  init_method: zeros
  out_act: linear
dataset_args:
  d_type: train
  normalize: True
  bounds: [0, 1]
  sequence_length: 1
  future_steps: 1
dataloader_args:
  num_workers: 0
  batch_size: 128
  shuffle: True
train_epochs: 30
evaluation: None